/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabletennisscores;

import data_classes.Player;
import data_classes.Team;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.event.EventListenerList;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Vilde
 */
public class RegisterPlayer extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPlayer
     */
    public RegisterPlayer() {
        initComponents();             
        if(!addTeamsToComboBox()) {
            showNoTeamsAvailable();
        }       
    }
    
    private boolean addTeamsToComboBox() {
        Boolean teamsAdded = false;
        ArrayList<Team> teams = TTScoreGUI1.manager.getTeamsWithOpenPlayerSlots();
        
        if(teams != null && teams.size() > 0) {
            teamsAdded = true;
        }
        Vector teamsVector = new Vector();
        for(Team t : teams) {          
            teamsVector.add(t);
            
        }
        final DefaultComboBoxModel model = new DefaultComboBoxModel(teamsVector);
        teamNameComboBox.setModel(model);
        teamNameComboBox.invalidate();
        return teamsAdded;
    }
    
    private void showNoTeamsAvailable() {
        errorLabel.setText("No teams with any open slots");
        playerNameLabel.setEnabled(false);
        teamNameComboBox.setEnabled(false);
        teamNameComboBox.addItem("No teams available");
        //teamNameComboBox.setVisible(false);      
        playerNameTextField.setEnabled(false);  
        //playerNameTextField.setVisible(false);
        addPlayerButton.setEnabled(false);
        //addPlayerButton.setVisible(false);               
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerNameLabel = new javax.swing.JLabel();
        teamNameComboBox = new javax.swing.JComboBox();
        playerNameTextField = new javax.swing.JTextField();
        addPlayerButton = new javax.swing.JButton();
        cancelFrameButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        playerNameLabel.setText("Player name");

        teamNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addPlayerButton.setText("Add player");
        addPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerButtonActionPerformed(evt);
            }
        });

        cancelFrameButton.setText("Cancel");
        cancelFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFrameButtonActionPerformed(evt);
            }
        });

        errorLabel.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cancelFrameButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                            .addComponent(addPlayerButton))
                        .addComponent(playerNameLabel)
                        .addComponent(playerNameTextField)
                        .addComponent(teamNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(playerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(teamNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelFrameButton)
                    .addComponent(addPlayerButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerButtonActionPerformed
        addPlayer();
    }//GEN-LAST:event_addPlayerButtonActionPerformed

    private void cancelFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFrameButtonActionPerformed
        closeWindow();
    }//GEN-LAST:event_cancelFrameButtonActionPerformed

    private void closeWindow() {
        this.setVisible(false);
        this.dispose();
    }
    
    private void addPlayer() {
        String playerName = playerNameTextField.getText().toString();
        if(playerName.isEmpty()) {
            //tell user to enter a name
        } else {
            
            Player player = new Player(playerName);
            Team team = (Team)teamNameComboBox.getSelectedItem();
            
            team.addPlayer(player);
            
            closeWindow();
        }
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlayerButton;
    private javax.swing.JButton cancelFrameButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JTextField playerNameTextField;
    private javax.swing.JComboBox teamNameComboBox;
    // End of variables declaration//GEN-END:variables

  
}
